'use strict';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const desenhos={inicio:'M3 10 12 3l9 7v11H3z M9 21v-8h6v8',aluno:'m2 8 10-5 10 5-10 5z M6 10v7q6 5 12 0v-7 M22 8v9',professor:'M4 3h16v13H4z M9 21l3-5 3 5 M8 7h8 M8 11h5',turmas:'M4 4h6v6H4z M14 4h6v6h-6z M4 14h6v6H4z M14 14h6v6h-6z',livros:'M12 5q-5-3-10 0v15q5-3 10 0 5-3 10 0V5q-5-3-10 0z M12 5v15',admin:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M18 8a3 3 0 0 1 0 6 M22 21v-2a4 4 0 0 0-3-4',busca:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',app:'M7 2h10v20H7z M11 18h2',check:'m4 12 5 5L20 6'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${desenhos[n]||desenhos.inicio}"/></svg>`;
const nomes={inicio:'Visão geral',aluno:'Alunos',professor:'Professores',turmas:'Turmas',livros:'Biblioteca',admin:'Equipe da secretaria'};
let sessao=null,csrf='',pagina='inicio',itens=[],turmas=[],professores=[],numeroPagina=0,consulta='',sequencia=0,temporizador=null,submitModal=null,toastTimer=null;
document.querySelectorAll('[data-page]').forEach(b=>{b.insertAdjacentHTML('afterbegin',icon(b.dataset.page));b.addEventListener('click',()=>ir(b.dataset.page));});
function erro(el,msg){el.textContent=msg;el.hidden=!msg;}
function aviso(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
async function api(acao,dados=null){
  let op={credentials:'same-origin',headers:{'X-Coord-Request':'1'}};let url='api.php';
  if(dados!==null){op.method='POST';op.headers['X-CSRF-Token']=csrf;if(dados instanceof FormData){dados.set('acao',acao);op.body=dados;}else{op.headers['Content-Type']='application/json';op.body=JSON.stringify({acao,...dados});}}
  else url+='?'+new URLSearchParams({acao});
  let r;try{r=await fetch(url,op);}catch{throw new Error('Não foi possível conectar. Confira se a API está aberta e tente novamente.');}
  let j;try{j=await r.json();}catch{throw new Error('O servidor não respondeu como esperado. Confira o limite do arquivo ou tente novamente.');}
  if(!r.ok){if(r.status===401&&acao!=='login')mostrarLogin();throw new Error(j.mensagem||'Não foi possível concluir.');}return j;
}
async function get(acao,params){return apiGet('api.php?'+new URLSearchParams({acao,...params}));}
async function apiGet(url){let r;try{r=await fetch(url,{credentials:'same-origin'});}catch{throw new Error('Conexão indisponível. Tente novamente.');}let j=await r.json();if(!r.ok){if(r.status===401)mostrarLogin();throw new Error(j.mensagem||'Não foi possível carregar.');}return j;}
function mostrarLogin(){sessao=null;csrf='';sequencia++;clearTimeout(temporizador);$('#modal').close();$('#app').hidden=true;$('#login').hidden=false;$('#inicial').hidden=true;$('#conteudo').replaceChildren();}
function entrar(r){sessao=r.usuario;csrf=r.csrf;$('#login').hidden=true;$('#app').hidden=false;$('#inicial').hidden=true;$('#nome-conta').textContent=sessao.nome;$('#avatar').textContent=sessao.nome[0].toUpperCase();ir(nomes[location.hash.slice(1)]?location.hash.slice(1):'inicio');}
$('#form-login').addEventListener('submit',async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;erro($('#erro-login'),'');try{const d=Object.fromEntries(new FormData(e.target));const r=await api('login',d);e.target.reset();entrar(r);}catch(x){erro($('#erro-login'),x.message);}finally{b.disabled=false;}});
$('#sair').onclick=async()=>{try{await api('logout',{});mostrarLogin();}catch(e){aviso(e.message);}};
$('#minha-conta').onclick=()=>formUsuario({...sessao,perfil:'admin'});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(sessao&&nomes[p]&&p!==pagina)ir(p);});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&sessao&&pagina==='livros'&&!$('#modal').open)carregar();});
function ir(p){pagina=p;numeroPagina=0;consulta='';history.replaceState(null,'','#'+p);document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('ativo',b.dataset.page===p);if(b.dataset.page===p)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('#local-atual').textContent=nomes[p];carregar();}
function topo(t,sub,acoes=''){return `<div class="pagina-topo"><div><span class="sobretitulo">ACADEMIA DE GÊNIOS</span><h1>${esc(t)}</h1><p>${esc(sub)}</p></div><div class="acoes">${acoes}</div></div>`;}
function vazio(t,p){return `<div class="vazio"><h3>${esc(t)}</h3><p>${esc(p)}</p></div>`;}
async function carregar(){
  const seq=++sequencia;clearTimeout(temporizador);const root=$('#conteudo');root.setAttribute('aria-busy','true');root.innerHTML='<div class="carregando" role="status">Carregando informações da escola…</div>';
  try{
    if(pagina==='inicio'){const d=await api('inicio');if(seq!==sequencia)return;renderInicio(d);}
    else if(['aluno','professor','admin'].includes(pagina)){
      const [d,t]=await Promise.all([get('usuarios',{perfil:pagina,q:consulta,pagina:numeroPagina}),api('turmas')]);if(seq!==sequencia)return;itens=d.itens;turmas=t.itens;professores=t.professores;renderUsuarios(d);
    }else if(pagina==='turmas'){const t=await api('turmas');if(seq!==sequencia)return;turmas=t.itens;professores=t.professores;renderTurmas();}
    else{const d=await api('livros');if(seq!==sequencia)return;itens=d.itens;renderLivros(d);if(d.pendentes.some(p=>['fila','processando'].includes(p.estado))&&!document.hidden)temporizador=setTimeout(()=>{if(!$('#modal').open)carregar();else temporizador=setTimeout(()=>{if(pagina==='livros')carregar();},10000);},5000);}
  }catch(e){if(seq===sequencia&&sessao){root.innerHTML=topo(nomes[pagina],'')+`<div class="erro" role="alert">${esc(e.message)}</div><button class="secundario" id="tentar">Tentar novamente</button>`;$('#tentar').onclick=carregar;}}
  finally{if(seq===sequencia)root.setAttribute('aria-busy','false');}
}
function renderInicio(d){
  const qtd=p=>d.contagens.filter(c=>c.perfil===p).reduce((a,c)=>a+Number(c.total),0);
  const cards=[['aluno','Alunos',qtd('aluno'),'contas ativas'],['professor','Professores',qtd('professor'),'educadores cadastrados'],['turmas','Turmas',d.turmas,'espaços de aprendizado'],['livros','Livros',d.livros,'edições ativas']];
  $('#conteudo').innerHTML=topo('Cada detalhe faz a diferença.','Acompanhe e organize as informações da sua escola.')+`<section class="boas-vindas"><div><span class="sobretitulo">TUDO EM UM SÓ LUGAR</span><h2>Olá, ${esc(sessao.nome.split(' ')[0])} 👋</h2><p>Prepare o caminho para aprender. Cadastre sua comunidade escolar e mantenha os materiais de estudo sempre por perto.</p></div><div class="selo-app">${icon('app')}Integrado ao app</div></section><div class="estatisticas">${cards.map(([i,t,n,s])=>`<article class="estatistica"><div class="stat-top">${t}<span class="stat-icone">${icon(i)}</span></div><strong>${Number(n).toLocaleString('pt-BR')}</strong><small>${s}</small></article>`).join('')}</div><div class="secao-titulo"><h3>Por onde vamos começar?</h3><span>Acesso rápido</span></div><div class="atalhos"><button class="atalho" data-ir="aluno">${icon('aluno')}<h3>Receber novos alunos</h3><p>Cadastre um aluno ou importe uma lista da escola em CSV.</p><span class="link">Gerenciar alunos →</span></button><button class="atalho" data-ir="professor">${icon('professor')}<h3>Organizar a equipe docente</h3><p>Mantenha as contas dos professores e suas turmas atualizadas.</p><span class="link">Ver professores →</span></button><button class="atalho" data-ir="livros">${icon('livros')}<h3>Ampliar a biblioteca</h3><p>Envie os PDFs que serão a base dos estudos e quizzes do app.</p><span class="link">Explorar biblioteca →</span></button></div><div class="faixa">${icon('check')}<p><strong>O mesmo banco, a mesma escola.</strong> As alterações feitas aqui são usadas pelo aplicativo.${Number(d.pendentes)?` Há ${Number(d.pendentes)} importação(ões) para acompanhar na biblioteca.`:''}</p></div>`;
  document.querySelectorAll('[data-ir]').forEach(b=>b.onclick=()=>ir(b.dataset.ir));
}
function renderUsuarios(d){
  const singular={aluno:'aluno',professor:'professor',admin:'usuário'}[pagina];
  const acoes=(pagina!=='admin'?'<button class="secundario" id="importar">↑ Importar CSV</button>':'')+`<button class="primario" id="novo">+ Adicionar ${singular}</button>`;
  const sub=pagina==='admin'?'Contas individuais para quem cuida da gestão escolar.':'Cadastros conectados ao aplicativo e à rotina da escola.';
  $('#conteudo').innerHTML=topo(nomes[pagina],sub,acoes)+`<section class="painel"><div class="filtros"><div class="busca">${icon('busca')}<input id="buscar" type="search" placeholder="Buscar por nome ou e-mail" aria-label="Buscar por nome ou e-mail" value="${esc(consulta)}" maxlength="100"></div><span class="quantidade">${Number(d.total)} ${Number(d.total)===1?'cadastro':'cadastros'}</span></div>${itens.length?`<div class="tabela-scroll"><table><thead><tr><th>Nome</th><th>E-mail de acesso</th><th>${pagina==='aluno'?'Turmas':'Perfil'}</th><th><span class="muted">Ações</span></th></tr></thead><tbody>${itens.map(u=>`<tr><td><div class="pessoa"><span class="avatar">${esc(u.nome.slice(0,2).toUpperCase())}</span><div><strong>${esc(u.nome)}</strong><small>ID ${Number(u.id_usuario)}</small></div></div></td><td class="email">${esc(u.email)}</td><td>${pagina==='aluno'?((u.turmas||'').split(',').filter(Boolean).map(id=>`<span class="pill">${esc(turmas.find(t=>String(t.id_turma)===id)?.nome_turma||'Turma '+id)}</span>`).join('')||'<span class="muted">Sem turma</span>'):`<span class="pill">${pagina==='admin'?'Secretaria':'Professor'}</span>`}</td><td><div class="botoes-linha"><button class="link-btn" data-edit="${Number(u.id_usuario)}">Editar</button>${Number(u.id_usuario)!==Number(sessao.id_usuario)?`<button class="link-btn danger" data-delete="${Number(u.id_usuario)}">Excluir</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:vazio('Nenhum cadastro encontrado',consulta?'Experimente outro nome ou e-mail.':'Adicione o primeiro cadastro usando o botão acima.')}<div class="paginacao"><span>Página ${numeroPagina+1} de ${Math.max(1,Math.ceil(Number(d.total)/30))}</span><div><button id="anterior" ${numeroPagina===0?'disabled':''}>← Anterior</button><button id="proxima" ${(numeroPagina+1)*30>=Number(d.total)?'disabled':''}>Próxima →</button></div></div></section>`;
  $('#novo').onclick=()=>formUsuario();if($('#importar'))$('#importar').onclick=formCsv;
  $('#buscar').addEventListener('input',e=>{consulta=e.target.value;clearTimeout(temporizador);temporizador=setTimeout(async()=>{numeroPagina=0;await carregar();const b=$('#buscar');if(b)b.focus();},450);});
  $('#anterior').onclick=()=>{numeroPagina--;carregar();};$('#proxima').onclick=()=>{numeroPagina++;carregar();};
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>formUsuario(itens.find(u=>String(u.id_usuario)===b.dataset.edit)));
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>excluirUsuario(itens.find(u=>String(u.id_usuario)===b.dataset.delete)));
}
function abrirModal(titulo,conteudo,submit,texto='Salvar'){
  $('#modal-titulo').textContent=titulo;$('#modal-conteudo').innerHTML=conteudo;$('#salvar-modal').textContent=texto;$('#salvar-modal').hidden=!submit;$('#salvar-modal').disabled=false;$('#salvar-modal').className='primario';erro($('#erro-modal'),'');submitModal=submit;$('#modal').showModal();
}
$('#fechar-modal').onclick=$('#cancelar-modal').onclick=()=>$('#modal').close();
$('#modal').addEventListener('close',()=>{$('#modal-conteudo').replaceChildren();submitModal=null;});
$('#form-modal').addEventListener('submit',async e=>{e.preventDefault();if(!submitModal)return;const submit=submitModal,b=$('#salvar-modal');b.disabled=true;erro($('#erro-modal'),'');try{await submit(new FormData(e.target));}catch(x){erro($('#erro-modal'),x.message);}finally{b.disabled=false;}});
function formUsuario(u=null){
  const perfil=u?(u.perfil==='aluno'||u.perfil==='professor'?u.perfil:'admin'):pagina;
  const nomePerfil=perfil==='admin'?'usuário da secretaria':perfil;
  const selecionadas=(u?.turmas||'').split(',');
  abrirModal(`${u?'Editar':'Adicionar'} ${nomePerfil}`,`<p class="dica">${u?'Mantenha os dados de acesso atualizados.':'A escola escolhe a senha inicial e a entrega ao usuário.'}</p><label>Nome completo<input name="nome" value="${esc(u?.nome)}" maxlength="100" required autocomplete="off"></label><label>E-mail de acesso<input name="email" type="email" value="${esc(u?.email)}" maxlength="150" required autocomplete="off"></label><label>${u?'Nova senha (opcional)':'Senha inicial'}<input name="senha" type="password" ${u?'':'required'} minlength="8" maxlength="72" autocomplete="new-password"><small>${u?'Deixe em branco para manter a senha. Alterá-la encerra as sessões abertas.':'Pelo menos 8 caracteres. A senha será salva somente como hash.'}</small></label>${perfil==='aluno'?`<fieldset><legend>Turmas do aluno</legend><div class="check-turmas">${turmas.length?turmas.map(t=>`<label><input type="checkbox" name="turmas" value="${Number(t.id_turma)}" ${selecionadas.includes(String(t.id_turma))?'checked':''}>${esc(t.nome_turma)} · ${esc(t.serie)} · ${esc(t.ano_letivo)}</label>`).join(''):'<p>Cadastre uma turma na seção Turmas para vinculá-la ao aluno.</p>'}</div></fieldset>`:''}${perfil==='admin'?'<label>Sua senha atual<input name="senha_atual" type="password" autocomplete="current-password" required><small>Confirme sua identidade para gerenciar as contas da secretaria.</small></label>':''}`,async fd=>{
    const d=Object.fromEntries(fd);d.perfil=perfil;d.id=Number(u?.id_usuario||0);d.turmas=fd.getAll('turmas').map(Number);
    const r=await api('salvar_usuario',d);$('#modal').close();if(r.relogin){mostrarLogin();aviso('Senha alterada. Entre novamente com a nova senha.');return;}if(d.id===Number(sessao.id_usuario)){sessao.nome=d.nome;sessao.email=d.email;$('#nome-conta').textContent=d.nome;}aviso('Cadastro salvo. Os dados já estão disponíveis para o app.');carregar();
  });
}
function excluirUsuario(u){
  const admin=pagina==='admin';abrirModal('Excluir acesso',`<p>Você está excluindo o acesso de <strong>${esc(u.nome)}</strong>.</p><div class="aviso">A conta deixará de aparecer nos cadastros e não poderá entrar no sistema. O histórico de estudos será preservado. O e-mail continuará reservado no histórico.</div>${admin?'<label>Sua senha atual<input name="senha_atual" type="password" required autocomplete="current-password"></label>':''}`,async fd=>{await api('excluir_usuario',{id:Number(u.id_usuario),senha_atual:fd.get('senha_atual')||''});$('#modal').close();aviso('Acesso excluído. Histórico preservado.');carregar();},'Excluir acesso');$('#salvar-modal').className='perigo';
}
function formCsv(){
  let confirmado=false;const perfil=pagina;
  abrirModal('Importar '+nomes[perfil].toLowerCase(),`<p class="dica">CSV em UTF-8, separado por ponto e vírgula ou vírgula. Até 500 cadastros por arquivo. Todos serão validados antes de salvar.</p><div class="aviso">Colunas: <strong>nome;email;senha;turmas</strong><br>A coluna turmas é opcional. Use os IDs da seção Turmas, separados por | para mais de uma turma. Não inclua contas da secretaria.</div><button type="button" class="link-btn" id="modelo">↓ Baixar modelo CSV</button><label>Arquivo CSV<input name="csv" type="file" accept=".csv,text/csv" required></label><div id="previa-csv"></div>`,async fd=>{
    fd.set('perfil',perfil);fd.set('confirmar',confirmado?'1':'0');const r=await api('csv',fd);
    if(r.importado){$('#modal').close();aviso(`${r.total} cadastros importados com sucesso.`);carregar();return;}
    confirmado=true;$('#salvar-modal').textContent=`Confirmar ${r.total} cadastros`;
    $('#previa-csv').innerHTML=`<div class="aviso">${r.total} cadastros válidos. Confira a prévia${r.total>10?' dos primeiros 10 registros':''} antes de confirmar. As senhas não são exibidas.</div><div class="tabela-scroll"><table class="previa"><thead><tr><th>Nome</th><th>E-mail</th></tr></thead><tbody>${r.previa.map(u=>`<tr><td>${esc(u.nome)}</td><td>${esc(u.email)}</td></tr>`).join('')}</tbody></table></div>`;
  },'Validar arquivo');
  $('[name=csv]').onchange=()=>{confirmado=false;$('#previa-csv').replaceChildren();$('#salvar-modal').textContent='Validar arquivo';};
  $('#modelo').onclick=()=>{const blob=new Blob(['\uFEFFnome;email;senha;turmas\r\n'],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`modelo-${perfil}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
function renderTurmas(){
  $('#conteudo').innerHTML=topo('Turmas','Organize as séries e vincule cada turma ao professor responsável.','<button class="primario" id="nova-turma">+ Adicionar turma</button>')+`<div class="painel">${turmas.length?`<div class="tabela-scroll"><table><thead><tr><th>Turma / ID para CSV</th><th>Série</th><th>Ano letivo</th><th>Professor responsável</th><th>Ações</th></tr></thead><tbody>${turmas.map(t=>`<tr><td><strong>${esc(t.nome_turma)}</strong><span class="pill">ID ${Number(t.id_turma)}</span></td><td>${esc(t.serie||'Não informada')}</td><td>${esc(t.ano_letivo)}</td><td>${esc(t.professor)}</td><td><button class="link-btn" data-turma="${Number(t.id_turma)}">Editar</button></td></tr>`).join('')}</tbody></table></div>`:vazio('Sua primeira turma começa aqui','Cadastre um professor e adicione uma turma para receber os alunos.')}</div>`;
  $('#nova-turma').onclick=()=>formTurma();document.querySelectorAll('[data-turma]').forEach(b=>b.onclick=()=>formTurma(turmas.find(t=>String(t.id_turma)===b.dataset.turma)));
}
function formTurma(t=null){
  abrirModal(t?'Editar turma':'Adicionar turma',`<label>Nome da turma<input name="nome_turma" required maxlength="80" value="${esc(t?.nome_turma)}" placeholder="Ex.: 1º A"></label><div class="dupla"><label>Série<input name="serie" required maxlength="40" value="${esc(t?.serie)}" placeholder="Ex.: 1ª série"></label><label>Ano letivo<input name="ano_letivo" required maxlength="10" value="${esc(t?.ano_letivo||new Date().getFullYear())}"></label></div><label>Professor responsável<select name="id_professor" required><option value="">Selecione um professor</option>${professores.map(p=>`<option value="${Number(p.id_usuario)}" ${p.id_usuario===t?.id_professor?'selected':''}>${esc(p.nome)}</option>`).join('')}</select><small>A edição do professor responsável transfere a turma e seus dados para o novo professor.</small></label>`,async fd=>{await api('salvar_turma',{...Object.fromEntries(fd),id:Number(t?.id_turma||0)});$('#modal').close();aviso('Turma salva.');carregar();});
}
function renderLivros(d){
  $('#conteudo').innerHTML=topo('Biblioteca da escola','Os livros didáticos são a fonte das explicações e dos quizzes.','<button class="primario" id="enviar-livro">↑ Adicionar livro PDF</button>')+`<div class="pendentes">${d.pendentes.map(j=>`<article class="pendente"><div><h3>${esc(j.titulo)} <span class="pill amarelo">${{fila:'Na fila',processando:'Processando',revisao:'Revisão necessária'}[j.estado]||esc(j.estado)}</span></h3><p>${esc(j.mensagem||'O PDF será preparado em segundo plano. Você pode continuar usando o painel.')}</p></div>${j.estado==='revisao'?`<button class="secundario" data-revisao="${Number(j.id)}">Revisar</button>`:''}</article>`).join('')}</div><section class="painel"><div class="filtros"><h3 class="muted">Acervo didático</h3><span class="quantidade">${itens.length} livros</span></div>${itens.length?`<div class="tabela-scroll"><table><thead><tr><th>Livro</th><th>Matéria</th><th>Conteúdo publicado</th><th>Status</th><th>Ações</th></tr></thead><tbody>${itens.map(l=>`<tr><td><strong>${esc(l.titulo)}</strong></td><td><span class="pill">${esc(l.materia)}</span></td><td>${Number(l.frentes)} frente(s) · ${Number(l.capitulos)} capítulo(s)</td><td><span class="pill ${Number(l.ativo)?'verde':'cinza'}">${Number(l.ativo)?'Ativo':'Inativo'}</span></td><td><div class="botoes-linha"><button class="link-btn" data-caps="${Number(l.id_livro)}">Capítulos</button><button class="link-btn" data-ativo="${Number(l.id_livro)}">${Number(l.ativo)?'Desativar':'Ativar'}</button></div></td></tr>`).join('')}</tbody></table></div>`:vazio('Vamos montar a biblioteca?','Envie um PDF para preparar seu conteúdo para os alunos.')}</section><p class="dica">Desativar um livro o remove das novas seleções de estudo, preservando os resultados anteriores.</p>`;
  $('#enviar-livro').onclick=formLivro;
  document.querySelectorAll('[data-caps]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await get('capitulos',{id:b.dataset.caps});abrirModal('Frentes e capítulos',r.itens.length?`<ul class="lista-capitulos">${r.itens.map(c=>`<li>${esc(c.titulo)}<small>${esc(c.frente)} · ${Number(c.revisado)?'Publicado':'Aguardando revisão'}</small></li>`).join('')}</ul>`:vazio('Conteúdo ainda não publicado','Este cadastro ainda não possui capítulos preparados.'),null);}catch(e){aviso(e.message);}finally{b.disabled=false;}});
  document.querySelectorAll('[data-ativo]').forEach(b=>b.onclick=()=>{const l=itens.find(l=>String(l.id_livro)===b.dataset.ativo),ativo=!Number(l.ativo);abrirModal(`${ativo?'Ativar':'Desativar'} livro`,`<p>${esc(l.titulo)}</p><p class="dica">${ativo?'O livro ficará disponível para novos estudos se possuir capítulos publicados.':'O livro deixará de aparecer em novas seleções. O histórico dos alunos será preservado.'}</p>`,async()=>{await api('livro_ativo',{id:Number(l.id_livro),ativo});$('#modal').close();aviso('Biblioteca atualizada.');carregar();},ativo?'Ativar livro':'Desativar livro');});
  document.querySelectorAll('[data-revisao]').forEach(b=>b.onclick=()=>revisarLivro(Number(b.dataset.revisao)));
}
function formLivro(){
  abrirModal('Adicionar livro didático',`<div class="aviso">O PDF será processado em segundo plano. Livros com marcadores de capítulos e texto selecionável são preparados automaticamente. Se precisar, você poderá informar a divisão em capítulos depois.</div><label>Título do livro<input name="titulo" maxlength="200" required placeholder="Ex.: Biologia · 1ª série"></label><label>Matéria<input name="materia" list="materias" maxlength="60" required placeholder="Ex.: Biologia"><datalist id="materias">${['Matemática','Português','Biologia','Física','Química','História','Geografia','Filosofia','Sociologia','Inglês'].map(m=>`<option value="${m}">`).join('')}</datalist><small>Use o mesmo nome da matéria já cadastrada para agrupar os livros no app.</small></label><label>Arquivo PDF<input type="file" name="pdf" accept="application/pdf,.pdf" required><small>Até 128 MB. Para PDFs digitalizados, aplique OCR antes do envio.</small></label>`,async fd=>{const f=fd.get('pdf');if(f.size>128*1024*1024)throw new Error('O arquivo deve ter até 128 MB.');$('#salvar-modal').textContent='Enviando PDF…';await api('enviar_livro',fd);$('#modal').close();aviso('PDF recebido. Acompanhe o processamento na biblioteca.');carregar();},'Enviar e preparar');
}
function revisarLivro(id){
  abrirModal('Revisar divisão do livro',`<p class="dica">Informe as páginas físicas do PDF, contando a capa como página 1. Os intervalos devem estar em ordem e não podem se sobrepor. Inclua somente o conteúdo do capítulo, sem gabaritos.</p><label>Frente; título do capítulo; página inicial; página final<textarea name="mapa" rows="8" required placeholder="Frente única; Capítulo 1 — Introdução; 3; 18&#10;Frente única; Capítulo 2 — Conceitos; 19; 32"></textarea><small>Uma linha por capítulo. Para livros com várias frentes, informe Frente 1, Frente 2 etc. nos capítulos correspondentes.</small></label><div class="aviso">Esta revisão resolve PDFs sem marcadores. Quando não houver texto selecionável, o PDF precisa passar por OCR antes de ser reenviado.</div>`,async fd=>{const mapa=fd.get('mapa').trim().split(/\r?\n/).map((l,i)=>{const p=l.split(';').map(x=>x.trim());if(p.length!==4||!/^\d+$/.test(p[2])||!/^\d+$/.test(p[3]))throw new Error(`Confira a linha ${i+1}. Use quatro campos separados por ponto e vírgula.`);return {frente:p[0],titulo:p[1],inicio:Number(p[2]),fim:Number(p[3])};});await api('reprocessar_livro',{id,mapa});$('#modal').close();aviso('Revisão enviada para processamento.');carregar();},'Salvar e reprocessar');
}
api('sessao').then(entrar).catch(e=>{mostrarLogin();if(!/Entre para acessar|sessão expirou/.test(e.message))erro($('#erro-login'),e.message);});
